#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Standalone Publisher for 9111.ru with Selenium anti-detection.
Uses cookies for authentication.
Reads source information from posts_meta.json (generated by Telegram_news bot).
"""

import os
import sys
import json
import time
import random
import shutil
import hashlib
import logging
from pathlib import Path
from datetime import datetime, date
from typing import Optional, Tuple, List

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.common.exceptions import TimeoutException, NoSuchElementException, WebDriverException, UnexpectedAlertPresentException
from webdriver_manager.chrome import ChromeDriverManager
from fake_useragent import UserAgent
import httpx

# ========== НАСТРОЙКИ ==========
POSTS_DIR = Path("data/posts")
PUBLISHED_DIR = Path("published")
STATE_FILE = Path("publisher_state.json")
COOKIES_FILE = Path("cookies_9111.ru.txt")
META_FILE = Path("posts_meta.json")
MAX_PUBLISH_PER_DAY = 8
MAX_PROXY_RETRIES = 3

PROXY_SOURCES = {
    'russia': 'https://raw.githubusercontent.com/Ganjo1st/Proctor/main/data/proxies_russia.txt',
    'global': 'https://raw.githubusercontent.com/Ganjo1st/Proctor/main/data/proxies_global.txt'
}

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


# ========== ПРОКСИ-ФУНКЦИИ ==========
def download_proxies() -> List[str]:
    all_proxies = []
    for source_name, url in PROXY_SOURCES.items():
        try:
            logger.info(f"📡 Загрузка {source_name} прокси...")
            response = httpx.get(url, timeout=15)
            if response.status_code == 200:
                proxies = [p.strip() for p in response.text.splitlines() if p.strip() and not p.startswith('#')]
                all_proxies.extend(proxies)
                logger.info(f"   ✅ Загружено {len(proxies)} прокси")
            else:
                logger.warning(f"   ⚠️ Ошибка {response.status_code}")
        except Exception as e:
            logger.warning(f"   ⚠️ Ошибка: {e}")
    unique_proxies = list(dict.fromkeys(all_proxies))
    logger.info(f"📊 Всего уникальных прокси: {len(unique_proxies)}")
    return unique_proxies


def test_proxy(proxy: str, timeout: int = 10) -> bool:
    try:
        proxy_url = proxy
        if not proxy_url.startswith(('http://', 'socks5://', 'socks4://')):
            proxy_url = f"http://{proxy_url}"
        transport = httpx.HTTPTransport(proxy=proxy_url)
        with httpx.Client(transport=transport, timeout=timeout) as client:
            response = client.get("https://9111.ru", follow_redirects=True)
            if response.status_code == 200 and len(response.text) > 1000:
                if "Access Denied" not in response.text and "blocked" not in response.text.lower():
                    return True
        return False
    except Exception:
        return False


def find_working_proxy(proxies_list: List[str]) -> Optional[str]:
    logger.info("🔍 Поиск рабочего прокси...")
    if not proxies_list:
        return None
    russian_proxies = [p for p in proxies_list if any(x in p for x in ['.ru', '178.', '176.', '188.', '193.', '194.', '195.', '212.', '213.', '217.', '5.', '89.', '109.', '176.'])]
    proxies_to_check = russian_proxies if russian_proxies else proxies_list
    if russian_proxies:
        logger.info(f"   Найдено {len(russian_proxies)} российских прокси")
    random.shuffle(proxies_to_check)
    for proxy in proxies_to_check[:20]:
        logger.info(f"   Проверяем: {proxy}")
        if test_proxy(proxy):
            logger.info(f"   ✅ Найден рабочий прокси: {proxy}")
            return proxy
        logger.info(f"   ❌ Не работает")
    logger.warning("⚠️ Нет рабочих прокси")
    return None


def parse_cookies_netscape(cookies_file: Path) -> List[dict]:
    cookies = []
    try:
        with open(cookies_file, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                parts = line.split('\t')
                if len(parts) >= 7:
                    import urllib.parse
                    value = urllib.parse.unquote(parts[6])
                    cookies.append({
                        'domain': parts[0],
                        'httpOnly': parts[1] == 'TRUE',
                        'path': parts[2],
                        'secure': parts[3] == 'TRUE',
                        'expiry': int(parts[4]) if parts[4] != '0' else None,
                        'name': parts[5],
                        'value': value
                    })
        logger.info(f"🍪 Загружено {len(cookies)} кук из {cookies_file}")
        return cookies
    except Exception as e:
        logger.error(f"❌ Ошибка парсинга кук: {e}")
        return []


def setup_driver_with_proxy(proxy: Optional[str] = None) -> webdriver.Chrome:
    options = Options()
    options.add_experimental_option("excludeSwitches", ["enable-automation", "enable-logging"])
    options.add_experimental_option('useAutomationExtension', False)
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_argument("--disable-infobars")
    options.add_argument("--disable-notifications")
    options.add_argument("--disable-extensions")
    options.add_argument("--disable-web-security")
    options.add_argument("--allow-running-insecure-content")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--headless=new")
    options.add_argument("--disable-gpu")
    
    ua = UserAgent()
    options.add_argument(f"--user-agent={ua.random}")
    sizes = [(1920, 1080), (1366, 768), (1536, 864), (1440, 900), (1280, 720)]
    width, height = random.choice(sizes)
    options.add_argument(f"--window-size={width},{height}")
    
    if proxy:
        proxy_url = proxy
        if not proxy_url.startswith(('http://', 'socks5://', 'socks4://')):
            proxy_url = f"http://{proxy_url}"
        options.add_argument(f'--proxy-server={proxy_url}')
        logger.info(f"🔌 Используем прокси: {proxy}")
    
    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=options)
    driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")
    driver.execute_script("Object.defineProperty(navigator, 'plugins', {get: () => [1,2,3,4,5]})")
    driver.execute_script("Object.defineProperty(navigator, 'languages', {get: () => ['ru-RU', 'ru']})")
    return driver


def login_with_cookies(driver, cookies_file: Path) -> bool:
    logger.info("   🍪 Авторизация через куки...")
    try:
        driver.get("https://9111.ru/pubs/add/title/")
        random_sleep(3, 5)
        if len(driver.find_elements(By.NAME, "email")) > 0:
            logger.warning("   ⚠️ Страница публикации показывает форму входа")
            return False
        if len(driver.find_elements(By.ID, "topic_name")) > 0:
            logger.info("   ✅ Авторизация подтверждена")
            return True
        return False
    except Exception as e:
        logger.error(f"   ❌ Ошибка установки кук: {e}")
        return False


# ========== ВСПОМОГАТЕЛЬНЫЕ ФУНКЦИИ ==========
def human_type(element, text, min_delay=0.07, max_delay=0.2):
    for char in text:
        element.send_keys(char)
        if random.random() < 0.1:
            time.sleep(random.uniform(0.2, 0.5))
        else:
            time.sleep(random.uniform(min_delay, max_delay))


def random_sleep(min_sec=2, max_sec=5):
    time.sleep(random.uniform(min_sec, max_sec))


def random_mouse_move(driver):
    try:
        action = ActionChains(driver)
        action.move_by_offset(random.randint(-100, 100), random.randint(-80, 80))
        action.perform()
        time.sleep(random.uniform(0.1, 0.3))
    except:
        pass


def safe_click(driver, element):
    try:
        driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", element)
        random_sleep(0.3, 0.8)
        driver.execute_script("arguments[0].click();", element)
        return True
    except Exception as e:
        logger.warning(f"   ⚠️ Не удалось кликнуть: {e}")
        return False


def handle_alert(driver):
    """Обрабатывает случайные алерты"""
    try:
        alert = driver.switch_to.alert
        text = alert.text
        logger.warning(f"   ⚠️ Обнаружен алерт: {text}")
        alert.accept()
        random_sleep(1, 2)
        return True
    except:
        return False


def generate_tags(text: str) -> str:
    tags = ["новости", "россия", "мир"]
    text_lower = text.lower()
    if "иран" in text_lower: tags.append("иран")
    if "европ" in text_lower: tags.append("европа")
    if "росси" in text_lower: tags.append("россия")
    if "война" in text_lower: tags.append("конфликт")
    if "китай" in text_lower: tags.append("китай")
    if "сша" in text_lower or "америк" in text_lower: tags.append("сша")
    if "израиль" in text_lower: tags.append("израиль")
    if "куба" in text_lower: tags.append("куба")
    return ", ".join(list(dict.fromkeys(tags))[:5])


def get_source_from_meta(post_folder: Path) -> Optional[str]:
    meta_file = post_folder / "meta.json"
    if meta_file.exists():
        try:
            with open(meta_file, 'r', encoding='utf-8') as f:
                meta = json.load(f)
                if meta.get('source_url'):
                    return meta['source_url']
        except:
            pass
    
    if META_FILE.exists():
        try:
            with open(META_FILE, 'r', encoding='utf-8') as f:
                meta_data = json.load(f)
            folder_name = post_folder.name
            if folder_name in meta_data.get("posts", {}):
                source_url = meta_data["posts"][folder_name].get("url")
                if source_url:
                    logger.info(f"   🔗 Найден источник из meta-файла")
                    return source_url
            folder_date = folder_name[:15]
            for key, value in meta_data.get("posts", {}).items():
                if folder_date in key or key.startswith(folder_date):
                    source_url = value.get("url")
                    if source_url:
                        logger.info(f"   🔗 Найден источник по дате")
                        return source_url
        except Exception as e:
            logger.warning(f"   ⚠️ Ошибка чтения meta-файла: {e}")
    return None


def add_source_to_content(content: str, source_url: Optional[str]) -> str:
    if not source_url:
        return content
    source_text = f"\n\n📌 Источник: {source_url}"
    if len(content) + len(source_text) > 4000:
        max_content_len = 4000 - len(source_text) - 100
        if len(content) > max_content_len:
            content = content[:max_content_len] + "..."
    return content + source_text


# ========== ФУНКЦИИ СОСТОЯНИЯ ==========
def load_state() -> dict:
    if STATE_FILE.exists():
        try:
            with open(STATE_FILE, 'r', encoding='utf-8') as f:
                return json.load(f)
        except:
            pass
    return {"published_titles": [], "last_reset_date": None}


def save_state(state: dict):
    with open(STATE_FILE, 'w', encoding='utf-8') as f:
        json.dump(state, f, ensure_ascii=False, indent=2)


def reset_daily_counter(state: dict) -> dict:
    today = date.today().isoformat()
    if state.get("last_reset_date") != today:
        state["published_titles"] = []
        state["last_reset_date"] = today
        logger.info("📅 Ежедневный счетчик сброшен.")
    return state


def can_publish_today(state: dict) -> bool:
    return len(state.get("published_titles", [])) < MAX_PUBLISH_PER_DAY


def is_already_published(title: str, state: dict) -> bool:
    title_hash = hashlib.md5(title.encode('utf-8')).hexdigest()
    for item in state.get("published_titles", []):
        if item.get("hash") == title_hash:
            return True
    return False


def mark_as_published(title: str, state: dict):
    state["published_titles"].append({
        "title": title,
        "hash": hashlib.md5(title.encode('utf-8')).hexdigest(),
        "date": datetime.now().isoformat()
    })
    save_state(state)


def parse_post_file(post_folder: Path) -> Tuple[Optional[str], Optional[str], Optional[Path]]:
    text_file = post_folder / "text.txt"
    if not text_file.exists():
        return None, None, None
    with open(text_file, 'r', encoding='utf-8') as f:
        content = f.read()
    lines = [line.strip() for line in content.split('\n') if line.strip()]
    if not lines:
        return None, None, None
    title = lines[0]
    import re
    emoji_pattern = re.compile("["
        u"\U0001F600-\U0001F64F"
        u"\U0001F300-\U0001F5FF"
        u"\U0001F680-\U0001F6FF"
        u"\U0001F1E0-\U0001F1FF"
        "]+", flags=re.UNICODE)
    title = emoji_pattern.sub(r'', title).strip()
    if len(title) > 150:
        title = title[:147] + "..."
    post_text = "\n".join(lines[1:]) if len(lines) > 1 else ""
    images = list(post_folder.glob("image.*"))
    image_path = images[0] if images else None
    return title, post_text, image_path


def upload_image(driver, image_path: Path) -> bool:
    """Загружает изображение через кнопку '+ Фото'"""
    try:
        photo_label = WebDriverWait(driver, 15).until(
            EC.element_to_be_clickable((By.XPATH, "//label[contains(@class, 'lite_editor_tools_btn') and contains(text(), '+ Фото')]"))
        )
        random_mouse_move(driver)
        safe_click(driver, photo_label)
        random_sleep(1, 2)

        file_input = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.ID, "editor_file_upload"))
        )
        file_input.send_keys(str(image_path.absolute()))
        logger.info(f"   ✅ Изображение загружено: {image_path.name}")
        random_sleep(3, 5)
        return True
        
    except TimeoutException:
        try:
            file_input = driver.find_element(By.CSS_SELECTOR, "input[type='file']")
            file_input.send_keys(str(image_path.absolute()))
            logger.info(f"   ✅ Изображение загружено (альтернативный способ)")
            random_sleep(3, 5)
            return True
        except Exception as e2:
            logger.warning(f"   ⚠️ Не удалось загрузить фото: {e2}")
            return False
    except Exception as e:
        logger.warning(f"   ⚠️ Ошибка загрузки фото: {e}")
        return False


def publish_post(driver, post_folder: Path, state: dict) -> bool:
    logger.info(f"\n📂 Пост: {post_folder.name}")

    title, post_text, image_path = parse_post_file(post_folder)
    if not title or not post_text:
        logger.warning("   ⚠️ Не удалось прочитать пост")
        return False

    if is_already_published(title, state):
        logger.info(f"   ⏭️ Заголовок уже опубликован")
        return False

    if not can_publish_today(state):
        logger.warning(f"   ⏸️ Достигнут лимит ({MAX_PUBLISH_PER_DAY}/день)")
        return False

    source_url = get_source_from_meta(post_folder)
    post_text = add_source_to_content(post_text, source_url)
    
    if source_url:
        logger.info(f"   🔗 Добавлен источник: {source_url}")
    else:
        logger.info(f"   ℹ️ Источник для поста не найден")

    logger.info(f"   📝 Публикуем: {title[:50]}...")
    logger.info(f"   📄 Длина текста: {len(post_text)} символов")

    try:
        if "/pubs/add/title/" not in driver.current_url:
            driver.get("https://9111.ru/pubs/add/title/")
            random_sleep(4, 6)

        # Проверяем алерты
        handle_alert(driver)

        if len(driver.find_elements(By.NAME, "email")) > 0:
            logger.error("   ❌ Мы на странице входа")
            return False

        # Заголовок
        title_input = WebDriverWait(driver, 20).until(
            EC.presence_of_element_located((By.ID, "topic_name"))
        )
        safe_click(driver, title_input)
        driver.execute_script("arguments[0].innerHTML = '';", title_input)
        human_type(title_input, title)
        random_sleep(2, 4)

        # Рубрика
        try:
            rubric = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable((By.ID, "rubric_id2"))
            )
            safe_click(driver, rubric)
            random_sleep(1, 2)
            driver.find_element(By.XPATH, "//option[contains(text(), 'Новости')]").click()
            logger.info("   ✅ Выбрана рубрика 'Новости'")
        except:
            pass
        random_sleep(2, 3)

        # Текст
        editor = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.ID, "lite_editor_container"))
        )
        safe_click(driver, editor)
        driver.execute_script("arguments[0].innerHTML = '';", editor)
        
        for p in post_text.split('\n'):
            if p.strip():
                driver.execute_script(f"arguments[0].innerHTML += '<p>{p.strip()}</p>';", editor)
                random_sleep(0.2, 0.5)

        random_sleep(3, 5)

        # Изображение
        if image_path and image_path.exists():
            upload_image(driver, image_path)

        # Теги
        try:
            tags_input = WebDriverWait(driver, 10).until(
                EC.presence_of_element_located((By.ID, "tag_list_input"))
            )
            driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", tags_input)
            random_sleep(0.5, 1)
            driver.execute_script("arguments[0].click();", tags_input)
            random_sleep(0.5, 1)
            tags_input.clear()
            human_type(tags_input, generate_tags(post_text))
            random_sleep(2, 4)
        except:
            logger.warning("   ⚠️ Не удалось ввести теги, продолжаем...")

        # Проверяем алерты перед публикацией
        handle_alert(driver)

        # Публикация
        publish_btn = WebDriverWait(driver, 15).until(
            EC.element_to_be_clickable((By.ID, "button_create_pubs"))
        )
        random_mouse_move(driver)
        safe_click(driver, publish_btn)
        random_sleep(8, 12)

        # Проверяем алерты после публикации
        handle_alert(driver)

        mark_as_published(title, state)
        logger.info(f"   🎉 Опубликовано!")

        PUBLISHED_DIR.mkdir(exist_ok=True)
        dest = PUBLISHED_DIR / post_folder.name
        shutil.move(str(post_folder), str(dest))
        logger.info(f"   📦 Пост перемещен в {PUBLISHED_DIR}")

        return True

    except UnexpectedAlertPresentException as e:
        logger.warning(f"   ⚠️ Алерт при публикации, пробуем продолжить")
        handle_alert(driver)
        return False
    except Exception as e:
        logger.error(f"   ❌ Ошибка: {e}")
        try:
            driver.save_screenshot("publish_error.png")
            logger.info("   📸 Скриншот сохранен как publish_error.png")
        except:
            pass
        return False


def get_all_posts() -> List[Path]:
    if not POSTS_DIR.exists():
        logger.warning(f"⚠️ Папка {POSTS_DIR} не существует")
        return []
    posts = [p for p in POSTS_DIR.iterdir() if p.is_dir()]
    logger.info(f"📊 Найдено папок-постов: {len(posts)}")
    if posts:
        logger.info(f"   Примеры: {', '.join([p.name[:50] for p in posts[:3]])}")
    return posts


def main():
    test_mode = os.getenv('TEST_PUBLISHER', 'false').lower() == 'true'
    
    logger.info("=" * 60)
    if test_mode:
        logger.info("🧪 ТЕСТОВЫЙ РЕЖИМ: Будет опубликован ТОЛЬКО ПРЕДПОСЛЕДНИЙ пост")
    else:
        logger.info("🚀 ЗАПУСК ПУБЛИКАТОРА")
    logger.info("=" * 60)

    # Загружаем свежий posts_meta.json
    try:
        response = httpx.get(
            'https://raw.githubusercontent.com/Ganjo1st/Telegram_news/main/posts_meta.json',
            timeout=10
        )
        if response.status_code == 200:
            with open('posts_meta.json', 'w', encoding='utf-8') as f:
                f.write(response.text)
            logger.info(f"✅ Файл posts_meta.json успешно загружен")
        else:
            logger.warning(f"⚠️ Не удалось загрузить posts_meta.json (статус {response.status_code})")
    except Exception as e:
        logger.warning(f"⚠️ Ошибка загрузки posts_meta.json: {e}")

    if not COOKIES_FILE.exists():
        logger.error(f"❌ Файл с куками не найден: {COOKIES_FILE}")
        sys.exit(1)

    all_posts = get_all_posts()
    if not all_posts:
        logger.info("📭 Нет постов для публикации.")
        return

    state = load_state()
    state = reset_daily_counter(state)

    if test_mode and len(all_posts) >= 2:
        test_posts = [all_posts[-2]]
        logger.info(f"🧪 ТЕСТ: выбран пост: {test_posts[0].name}")
    else:
        test_posts = all_posts

    new_posts = []
    for post in test_posts:
        title, _, _ = parse_post_file(post)
        if title and not is_already_published(title, state):
            new_posts.append(post)
            logger.info(f"   ✅ Новый пост: {title[:50]}...")
        elif title:
            logger.info(f"   ⏭️ Уже опубликован: {title[:50]}...")

    logger.info(f"\n📊 Новых постов: {len(new_posts)} (макс. {MAX_PUBLISH_PER_DAY}/день)")

    if not new_posts:
        logger.info("📭 Нет новых постов.")
        return

    all_proxies = download_proxies()
    current_proxy = find_working_proxy(all_proxies)
    
    if not current_proxy:
        logger.error("❌ Нет рабочих прокси. Публикация невозможна.")
        return
    
    driver = setup_driver_with_proxy(current_proxy)
    
    cookies = parse_cookies_netscape(COOKIES_FILE)
    if not cookies:
        logger.error("❌ Не удалось загрузить куки")
        driver.quit()
        return
    
    driver.get("https://9111.ru/pubs/add/title/")
    random_sleep(2, 3)
    
    for cookie in cookies:
        try:
            cookie_dict = {
                'name': cookie['name'],
                'value': cookie['value'],
                'domain': cookie['domain'],
                'path': cookie['path'],
                'secure': cookie['secure']
            }
            if cookie['expiry'] and cookie['expiry'] > 0:
                cookie_dict['expiry'] = cookie['expiry']
            driver.add_cookie(cookie_dict)
            logger.info(f"      ✅ Кука: {cookie['name']}")
        except Exception as e:
            logger.debug(f"      ⚠️ {cookie['name']}: {e}")
    
    driver.refresh()
    random_sleep(3, 5)
    
    if len(driver.find_elements(By.ID, "topic_name")) == 0:
        logger.error("❌ Авторизация не удалась")
        driver.quit()
        return
    
    logger.info("✅ Авторизация по кукам успешна!")
    
    published_count = 0
    proxy_fail_count = 0
    
    try:
        for i, post_folder in enumerate(new_posts, 1):
            if not can_publish_today(state):
                logger.warning(f"⏸️ Лимит {MAX_PUBLISH_PER_DAY} достигнут.")
                break
            
            logger.info(f"\n{'='*50}")
            logger.info(f"📌 Пост {i}/{len(new_posts)}")
            
            success = publish_post(driver, post_folder, state)
            
            if success:
                published_count += 1
                proxy_fail_count = 0
                if i < len(new_posts):
                    pause = random.randint(60, 120)
                    logger.info(f"⏳ Пауза {pause} сек...")
                    time.sleep(pause)
            else:
                proxy_fail_count += 1
                logger.warning(f"   ⚠️ Ошибка публикации (попытка {proxy_fail_count}/{MAX_PROXY_RETRIES})")
                
                if proxy_fail_count >= MAX_PROXY_RETRIES:
                    logger.info("   🔄 Смена прокси...")
                    driver.quit()
                    available_proxies = [p for p in all_proxies if p != current_proxy]
                    current_proxy = find_working_proxy(available_proxies)
                    if current_proxy:
                        driver = setup_driver_with_proxy(current_proxy)
                        driver.get("https://9111.ru/pubs/add/title/")
                        random_sleep(2, 3)
                        for cookie in cookies:
                            try:
                                cookie_dict = {
                                    'name': cookie['name'],
                                    'value': cookie['value'],
                                    'domain': cookie['domain'],
                                    'path': cookie['path'],
                                    'secure': cookie['secure']
                                }
                                if cookie['expiry'] and cookie['expiry'] > 0:
                                    cookie_dict['expiry'] = cookie['expiry']
                                driver.add_cookie(cookie_dict)
                            except:
                                pass
                        driver.refresh()
                        random_sleep(3, 5)
                        proxy_fail_count = 0
                        logger.info("   ✅ Прокси сменен, продолжаем...")
                    else:
                        logger.error("   ❌ Нет рабочих прокси. Остановка.")
                        break
                else:
                    time.sleep(30)
        
        logger.info(f"\n📊 ИТОГИ: Опубликовано {published_count} из {len(new_posts)} новых постов.")
        
    finally:
        driver.quit()


if __name__ == "__main__":
    main()
